"""
chm.states
==========
Derivation of the five functional states from the cusp geometry, and of the
5x5 transition kernel from Kramers escape rates.

This module contains what we regard as the paper's second structural
contribution.  In the prior literature (and in the first draft of this work)
the five states were *assigned from experimental condition labels*, which makes
any subsequent "prediction" of those states circular: the transition matrix
merely recovers the block design of the protocol.

Here the states are read off the geometry of the fitted dynamical system, and
the experimental labels are used only as EXTERNAL VALIDATION.

Definitions
-----------
Let x_t be the latent load, a_t the splitting factor, b_t the drive.

    basin(x_t)        lower (functional)  vs upper (overloaded)
    B_t = 4a^3 - 27b^2  bistability index: > 0 iff an alternative attractor exists
    b_dn = -b_c(a)      lower fold: below this the upper basin ceases to exist

                | monostable (B <= 0)            | bistable (B > 0)
    ------------+--------------------------------+---------------------------
    lower basin | CALM   (b <= b_med)            | STUCK
                | FOCUSED(b >  b_med)            |
    upper basin | OVERLOADED                     | OVERLOADED (b >  0)
                |                                | RECOVERING (b <= 0)

Reading of the two non-obvious states:

STUCK      the person is still functioning, but an overloaded attractor now
           coexists: they are one perturbation away from tipping.  This is,
           to our knowledge, the first precise mathematical definition of the
           "stuck / on the edge" state that qualitative work describes.

RECOVERING the person remains in the high-load basin even though current demand
           has fallen back below the level that would have put them there.
           They are held up purely by hysteresis.  That is exactly the clinical
           description of delayed recovery, and here it is a geometric fact
           rather than a label.
"""

from __future__ import annotations

import numpy as np

from . import potential as P
from .model import STATES

__all__ = [
    "STATES",
    "STATE_INDEX",
    "assign_states",
    "transition_matrix_from_params",
    "empirical_transition_matrix",
    "dwell_times",
]

STATE_INDEX = {s: i for i, s in enumerate(STATES)}


def assign_states(x, a, b, b_med=None):
    """
    Map (x_t, a_t, b_t) to the five functional states.

    Parameters
    ----------
    x, a, b : arrays of equal length
    b_med   : split point between calm and focused.  Defaults to the within-
              series median drive, which makes the calm/focused distinction
              person-relative (a design choice we test for sensitivity).

    Returns
    -------
    np.ndarray of dtype '<U10' with one label per time step.
    """
    x = np.asarray(x, float)
    a = np.asarray(a, float)
    b = np.asarray(b, float)
    if b_med is None:
        b_med = float(np.nanmedian(b))

    bist = P.is_bistable(a, b)
    s = P.saddle(a, b)
    # in the monostable case the single attractor's sign decides the basin
    upper = np.where(np.isnan(s), x > 0.0, x > s)

    out = np.empty(x.shape, dtype="<U10")

    # ---- lower basin ------------------------------------------------------ #
    lower = ~upper
    out[lower & ~bist & (b <= b_med)] = "calm"
    out[lower & ~bist & (b > b_med)] = "focused"
    out[lower & bist] = "stuck"

    # ---- upper basin ------------------------------------------------------ #
    out[upper & ~bist] = "overloaded"
    out[upper & bist & (b > 0)] = "overloaded"
    out[upper & bist & (b <= 0)] = "recovering"

    # numerical fallback (should not trigger; kept so the array is never empty)
    out[out == ""] = "calm"
    return out


def transition_matrix_from_params(a, b, sigma, dt=1.0, b_med=None):
    """
    Model-implied 5x5 transition matrix at a given operating point (a, b).

    The between-basin entries come from Kramers escape rates,

        P(escape in dt) = 1 - exp(-r dt),
        r = sqrt(|V''(x_start) V''(x_saddle)|)/(2 pi) * exp(-2 dV / sigma^2),

    and the within-basin entries from the deterministic geometry (which of
    calm / focused / stuck applies at this (a, b)).  Note the parameter count:
    the whole matrix is generated by (a, b, sigma), i.e. by the ~8 dynamical
    parameters evaluated at the current covariates, instead of by 20 free
    counted probabilities.
    """
    a = float(a)
    b = float(b)
    bist = bool(P.is_bistable(a, b))

    if bist:
        p_up = 1.0 - np.exp(-P.kramers_rate(a, b, sigma, "up") * dt)
        p_dn = 1.0 - np.exp(-P.kramers_rate(a, b, sigma, "down") * dt)
    else:
        # no barrier: the drive alone decides which single attractor exists
        p_up = 1.0 if b > 0 else 0.0
        p_dn = 0.0 if b > 0 else 1.0

    if b_med is None:
        b_med = 0.0
    lower_label = "stuck" if bist else ("focused" if b > b_med else "calm")
    upper_label = "recovering" if (bist and b <= 0) else "overloaded"

    M = np.zeros((5, 5))
    li, ui = STATE_INDEX[lower_label], STATE_INDEX[upper_label]

    for s in STATES:
        i = STATE_INDEX[s]
        if s in ("overloaded", "recovering"):     # currently in the upper basin
            M[i, li] = p_dn
            M[i, ui] += 1.0 - p_dn
        else:                                     # currently in the lower basin
            M[i, ui] = p_up
            M[i, li] += 1.0 - p_up

    rs = M.sum(axis=1, keepdims=True)
    return M / np.where(rs > 0, rs, 1.0)


def empirical_transition_matrix(states, laplace=0.0):
    """Row-normalised count matrix over the canonical state ordering."""
    states = np.asarray(states)
    C = np.full((5, 5), float(laplace))
    for i in range(len(states) - 1):
        a = STATE_INDEX.get(str(states[i]))
        b = STATE_INDEX.get(str(states[i + 1]))
        if a is not None and b is not None:
            C[a, b] += 1.0
    rs = C.sum(axis=1, keepdims=True)
    return C / np.where(rs > 0, rs, 1.0)


def dwell_times(states, target):
    """
    Lengths of consecutive runs in `target`.

    Used for PREDICTION P3: a homogeneous Markov chain forces geometric dwell
    times; the CHM model, because the slow variable keeps a_t elevated, predicts
    over-dispersion (a heavier right tail).  That difference is what we test.
    """
    states = np.asarray(states).astype(str)
    runs, cur = [], 0
    for s in states:
        if s == target:
            cur += 1
        elif cur:
            runs.append(cur)
            cur = 0
    if cur:
        runs.append(cur)
    return np.array(runs, float)
